'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutoUpdaterVB.NET.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property clock_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property clock_go_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_go_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property clock_go1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_go1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property clock_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property download_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property download1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property DownloadDialog() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DownloadDialog", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading at {0}/s.
        '''</summary>
        Public ReadOnly Property DownloadSpeedMessage() As String
            Get
                Return ResourceManager.GetString("DownloadSpeedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checksum differs.
        '''</summary>
        Public ReadOnly Property FileIntegrityCheckFailedCaption() As String
            Get
                Return ResourceManager.GetString("FileIntegrityCheckFailedCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File integrity check failed and reported some errors..
        '''</summary>
        Public ReadOnly Property FileIntegrityCheckFailedMessage() As String
            Get
                Return ResourceManager.GetString("FileIntegrityCheckFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property hand_point() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hand_point", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsupported Hash Algorithm.
        '''</summary>
        Public ReadOnly Property HashAlgorithmNotSupportedCaption() As String
            Get
                Return ResourceManager.GetString("HashAlgorithmNotSupportedCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hash algorithm provided in the XML file is not supported..
        '''</summary>
        Public ReadOnly Property HashAlgorithmNotSupportedMessage() As String
            Get
                Return ResourceManager.GetString("HashAlgorithmNotSupportedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Check Failed.
        '''</summary>
        Public ReadOnly Property UpdateCheckFailedCaption() As String
            Get
                Return ResourceManager.GetString("UpdateCheckFailedCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a problem reaching update server. Please check your internet connection and try again later..
        '''</summary>
        Public ReadOnly Property UpdateCheckFailedMessage() As String
            Get
                Return ResourceManager.GetString("UpdateCheckFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Unavailable.
        '''</summary>
        Public ReadOnly Property UpdateUnavailableCaption() As String
            Get
                Return ResourceManager.GetString("UpdateUnavailableCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no update available. Please try again later..
        '''</summary>
        Public ReadOnly Property UpdateUnavailableMessage() As String
            Get
                Return ResourceManager.GetString("UpdateUnavailableMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property ZipExtractor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ZipExtractor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
